services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt-H5
    ports:
      - "1883:1883"  # MQTT port
      - "9001:9001"  # WebSocket port
    volumes:
      - mosquitto_data:/mosquitto/data
    command: >
      -v
      -p 1883
      -p 9001
      -allow_anonymous true
      -listener 1883 0.0.0.0
      -listener 9001 0.0.0.0

volumes:
  mosquitto_data:
