services:
  timescaledb-csharp:
    image: timescale/timescaledb:latest-pg12
    container_name: timescaledb
    environment:
      - POSTGRES_DB=CSharpDatabase  # Navnet på din database
      - POSTGRES_USER=CSharpAdmin     # Brugernavn
      - POSTGRES_PASSWORD=CSharpAdmin # Adgangskode
    ports:
      - "5432:5432"               # Eksponerer porten
    volumes:
      - timescaledb_data:/var/lib/postgresql/data # Vedholdende data

  timescaledb-golang:
    image: timescale/timescaledb:latest-pg12
    container_name: timescaledb-golang
    environment:
      - POSTGRES_DB=GolangDatabase  # Navnet på din database
      - POSTGRES_USER=GolangAdmin     # Brugernavn
      - POSTGRES_PASSWORD=GolangAdmin # Adgangskode
    ports:
      - "5433:5432"               # Eksponerer porten
    volumes:
      - timescaledb_data:/var/lib/postgresql/data # Vedholdende data

volumes:
  timescaledb_data:
